# Generated by Django 2.2.4 on 2019-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_video_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.CharField(default='Action', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='reference_Id',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
