# Generated by Django 2.2.4 on 2019-09-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_video_desciption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
